---
version: "3.8"
services:
  main:
    image: commerceblock/lockbox:d07d4f2
    deploy:
      replicas: 1
      restart_policy:
              condition: none
    ports:
      - "8000:8000"
    environment:
      SGX_MODE: HW
      SGX_SDK: /opt/intel/sgxsdk
      LD_LIBRARY_PATH: /opt/intel/sgxsdk/sdk_libs
      LOCKBOX_DB_PATH: /tmp/lockbox
      LOCKBOX_KEY_DB_PATH: /tmp/lockbox_key
      LOCKBOX_INIT_PATH: /tmp/pub/init_pub.dat
      LOCKBOX_ENC_INDEX: 1
      LOCKBOX_URL_SRC: http://main:8000
      LOCKBOX_URL_DST: http://10.6.6.9:8000
    devices:
      - "/dev/isgx:/dev/isgx"
    volumes:
      - /data/lockbox_0:/tmp/lockbox
      - /data/lockbox_key_0:/tmp/lockbox_key
      - /data/pub:/tmp/pub
    command: >
      bash -c "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/sgx-aesm-service/aesm/ /opt/intel/sgx-aesm-service/aesm/aesm_service;
                /opt/lockbox/bin/server_exec"
