[target.x86_64-fortanix-unknown-sgx]
runner = "ftxsgx-runner-cargo"
linker = "x86_64-unknown-linux-gnu-ld"

[build]
target = "x86_64-fortanix-unknown-sgx"

[env]
CC_x86_64-fortanix-unknown-sgx = "x86_64-unknown-linux-gnu-gcc"
AR_x86_64-fortanix-unknown-sgx = "x86_64-unknown-linux-gnu-ar"

[rust]
lld = true
