#![feature(stdsimd)]
[workspace]
members = ["server", "client", "shared"]
[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
sgx_types = { path = "../../sgx/sgx_types" }
sgx_urts = { path = "../../sgx/sgx_urts" }

