endpoint = "http://127.0.0.1:8000"
electrum_server = "127.0.0.1:60401" # Empty string for Mock Electrum server
testing_mode = "false" # Use testing wallet
network = "regtest"
daemon_address = "/tmp/rustd.sock"
[tor]
enable = false
proxy = "socks5h://127.0.0.1:9050"
