[package]
name = "lockbox_enclave"
version = "1.0.0"
authors = ["The Teaclave Authors"]

[lib]
name = "lockbox_enclave_lib"
path = "src/lib.rs"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
serde = { git = "https://github.com/mesalock-linux/serde-sgx" }
sgx_serialize_derive = { rev="v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
serde_derive = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_cbor = { git = "https://github.com/mesalock-linux/cbor-sgx" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { rev="v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git"}
sgx_trts = { rev="v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tseal = { rev="v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_rand = { rev="v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_serialize = { rev="v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
