[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["The Teaclave Authors"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[dependencies]
serde = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_derive = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_cbor = { git = "https://github.com/mesalock-linux/cbor-sgx" }

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git", tag="v1.1.2" }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["backtrace"], tag="v1.1.2" }
sgx_trts = { git = "https://github.com/apache/teaclave-sgx-sdk.git", tag="v1.1.2" }
sgx_tseal = { git = "https://github.com/apache/teaclave-sgx-sdk.git", tag="v1.1.2" }
sgx_rand = { git = "https://github.com/apache/teaclave-sgx-sdk.git", tag="v1.1.2" }
[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
sgx_alloc = { path = "../../sgx/sgx_alloc" }
sgx_build_helper = { path = "../../sgx/sgx_build_helper" }
sgx_cov = { path = "../../sgx/sgx_cov" }
sgx_crypto_helper = { path = "../../sgx/sgx_crypto_helper" }
sgx_libc = { path = "../../sgx/sgx_libc" }
sgx_rand = { path = "../../sgx/sgx_rand" }
sgx_rand_derive = { path = "../../sgx/sgx_rand_derive" }
sgx_serialize = { path = "../../sgx/sgx_serialize" }
sgx_serialize_derive = { path = "../../sgx/sgx_serialize_derive" }
sgx_serialize_derive_internals = { path = "../../sgx/sgx_serialize_derive_internals" }
sgx_tcrypto = { path = "../../sgx/sgx_tcrypto" }
sgx_tcrypto_helper = { path = "../../sgx/sgx_tcrypto_helper" }
sgx_tdh = { path = "../../sgx/sgx_tdh" }
sgx_tkey_exchange = { path = "../../sgx/sgx_tkey_exchange" }
sgx_tprotected_fs = { path = "../../sgx/sgx_tprotected_fs" }
sgx_trts = { path = "../../sgx/sgx_trts" }
sgx_tse = { path = "../../sgx/sgx_tse" }
sgx_tseal = { path = "../../sgx/sgx_tseal" }
sgx_tstd = { path = "../../sgx/sgx_tstd" }
sgx_tunittest = { path = "../../sgx/sgx_tunittest" }
sgx_types = { path = "../../sgx/sgx_types" }
sgx_ucrypto = { path = "../../sgx/sgx_ucrypto" }
sgx_unwind = { path = "../../sgx/sgx_unwind" }
sgx_urts = { path = "../../sgx/sgx_urts" }
